
package com.afpa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MonAgeService", targetNamespace = "http://afpa.com/", wsdlLocation = "http://Isidore:8080/LabAge/MonAgeService?wsdl")
public class MonAgeService
    extends Service
{

    private final static URL MONAGESERVICE_WSDL_LOCATION;
    private final static WebServiceException MONAGESERVICE_EXCEPTION;
    private final static QName MONAGESERVICE_QNAME = new QName("http://afpa.com/", "MonAgeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://Isidore:8080/LabAge/MonAgeService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MONAGESERVICE_WSDL_LOCATION = url;
        MONAGESERVICE_EXCEPTION = e;
    }

    public MonAgeService() {
        super(__getWsdlLocation(), MONAGESERVICE_QNAME);
    }

    public MonAgeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MONAGESERVICE_QNAME, features);
    }

    public MonAgeService(URL wsdlLocation) {
        super(wsdlLocation, MONAGESERVICE_QNAME);
    }

    public MonAgeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MONAGESERVICE_QNAME, features);
    }

    public MonAgeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MonAgeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MonAge
     */
    @WebEndpoint(name = "MonAgePort")
    public MonAge getMonAgePort() {
        return super.getPort(new QName("http://afpa.com/", "MonAgePort"), MonAge.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MonAge
     */
    @WebEndpoint(name = "MonAgePort")
    public MonAge getMonAgePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://afpa.com/", "MonAgePort"), MonAge.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MONAGESERVICE_EXCEPTION!= null) {
            throw MONAGESERVICE_EXCEPTION;
        }
        return MONAGESERVICE_WSDL_LOCATION;
    }

}
